// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRCPsvn1aiBhJ96j6Rrqib55CmrASBG-g',
    appId: '1:462172029648:web:563545437548ded569d4d5',
    messagingSenderId: '462172029648',
    projectId: 'aiuzunov-diploma-thesis',
    authDomain: 'aiuzunov-diploma-thesis.firebaseapp.com',
    databaseURL: 'https://aiuzunov-diploma-thesis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aiuzunov-diploma-thesis.appspot.com',
    measurementId: 'G-S4PZC8Z0XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8nDrMdaNkmsD4165z8RayjaeR_ACVBsI',
    appId: '1:462172029648:android:bb72471c7e4cedf969d4d5',
    messagingSenderId: '462172029648',
    projectId: 'aiuzunov-diploma-thesis',
    databaseURL: 'https://aiuzunov-diploma-thesis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aiuzunov-diploma-thesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAne7fd8IC-P7C7zRcoUnL0jkhSJkxTpsA',
    appId: '1:462172029648:ios:b580b61216caf55b69d4d5',
    messagingSenderId: '462172029648',
    projectId: 'aiuzunov-diploma-thesis',
    databaseURL: 'https://aiuzunov-diploma-thesis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aiuzunov-diploma-thesis.appspot.com',
    iosClientId: '462172029648-978qsijl7evpfn96csuc7lo7nla00v0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAne7fd8IC-P7C7zRcoUnL0jkhSJkxTpsA',
    appId: '1:462172029648:ios:b580b61216caf55b69d4d5',
    messagingSenderId: '462172029648',
    projectId: 'aiuzunov-diploma-thesis',
    databaseURL: 'https://aiuzunov-diploma-thesis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aiuzunov-diploma-thesis.appspot.com',
    iosClientId: '462172029648-978qsijl7evpfn96csuc7lo7nla00v0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipesApp',
  );
}
